version: '3.9'

services:
  rabbitmq:
    image: mobarrio/opsgenie-rabbitmq:0.0.1
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret_cookie}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

    deploy:
      restart_policy:
        condition: on-failure

    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

    ports:
      - 15672:15672
      - 5672:5672

    networks:
      - public

  opsgenie:
    image: mobarrio/opsgenie-daemon:0.0.1
    container_name: ops-daemon

    environment:
      RABBITMQ_DEFAULT_SERVER: 'rabbitmq'
      RABBITMQ_DEFAULT_PORT: 5672
      RABBITMQ_DEFAULT_USERNAME: 'guest'
      RABBITMQ_DEFAULT_PASSWORD: 'guest'
      TZ: 'Europe/Madrid'
      #OPSGENIE_API_KEY: '<DEFAULT API KEY>'
      OPSGENIE_API_URL: 'https://api.eu.opsgenie.com'
      #OPSGENIE_CLOSER_USER: 'mi@dominio.com'
      OPSGENIE_CLOSER_SOURCE: 'System'
      OPSGENIE_CLOSER_NOTEe: 'Alert was unnecessary, closed by System'

    env_file: .env

    environment:
      rmq_server: 'rabbitmq'

    deploy:
      restart_policy:
        condition: on-failure

    depends_on:
      rabbitmq:
        condition: service_healthy

    networks:
      - public

networks:
  public:
