FROM python:3.9
WORKDIR /app
COPY requirements.txt requirements.txt
COPY opsgenie-daemon.py opsgenie-daemon.py
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt
CMD [ "python", "-u", "opsgenie-daemon.py" ]
