version: '3.9'

services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile-rabbitmq

    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret_cookie}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

    deploy:
      restart_policy:
        condition: on-failure

    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      #test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

    ports:
      - 15672:15672
      - 5672:5672

    networks:
      - public

  opsgenie:
    build: 
      context: .
      dockerfile: Dockerfile-ops

    container_name: ops
      
    env_file: .env

    deploy:
      restart_policy:
        condition: on-failure

    depends_on:
      rabbitmq:
        condition: service_healthy

    networks:
      - public

networks:
  public:
