#!/usr/bin/env python

import sys
import os
import logging
import argparse
import time
import datetime
import opsgenie_sdk
import pika
import json
from datetime import timezone, datetime, timedelta
from dateutil import tz
from distutils.util import strtobool
from pprint import pprint
from opsgenie_sdk.rest import ApiException
from dotenv import load_dotenv
load_dotenv(".env")

f = datetime.now()
print(f.strftime('%s'))
print(int(f.timestamp()))
